In [1]:
import pandas as pd

df = pd.read_csv("tiktok_data.csv")
df.head()

,date,likes,views,sound
0,2026-07-06 20:00:30 UTC,4908,41700,floating signal - alyzea
1,2026-07-06 01:28:45 UTC,1424,14000,Shadow of the Coffee Bean - Penelope the Perfe...
2,2026-07-04 03:19:57 UTC,32865,377300,som original - surfingoversociety
3,2026-06-07 02:49:06 UTC,3089,26100,original sound - b.ant4
4,2026-05-23 03:53:19 UTC,2052,17000,floating signal - alyzea

In [2]:
df["date"] = pd.to_datetime(df["date"])
df["hour"] = df["date"].dt.hour
df["weekday"] = df["date"].dt.dayofweek
df.head()

,date,likes,views,sound,hour,weekday
0,2026-07-06 20:00:30+00:00,4908,41700,floating signal - alyzea,20,0
1,2026-07-06 01:28:45+00:00,1424,14000,Shadow of the Coffee Bean - Penelope the Perfe...,1,0
2,2026-07-04 03:19:57+00:00,32865,377300,som original - surfingoversociety,3,5
3,2026-06-07 02:49:06+00:00,3089,26100,original sound - b.ant4,2,6
4,2026-05-23 03:53:19+00:00,2052,17000,floating signal - alyzea,3,5